### PR TITLE
uncached files shown as broken symlinks in the fuse offline mode

### LINKED ISSUE #65: Proposal to show uncached files as simlinks with fuse
When we do fuse mount with `-o` (offline) option.
1. Let's assign file mode as symlink to uncashed files.
This way when someone asks for a listing, there will be nice visual (red font with colored list command) to remind that this file is uncached.

2. We might even show a link to the missing ipfs hash.

Item 2 is some extra work, but item 1 is easy. I already have a draft for it.

@sahib what do you think?

### PR DESCRIPTION
**Pull request by evgmik**
Closes #65

Additional/necessary changes

Added
func (fi *File) Readlink(ctx context.Context, req *fuse.ReadlinkRequest) (string, error)
to resolve name of the link.

Changed default write permissions
from `rwx rwx rwx` to `rw- r-- ---`

### CODE REVIEW

File: fuse/file.go [hunk 1]
```diff
@@ -36,7 +37,18 @@ func (fi *File) Attr(ctx context.Context, attr *fuse.Attr) error {
 	}
 	debugLog("exec file attr: %v", fi.path)
 
-	attr.Mode = 0755
+	var filePerm os.FileMode = 0640
+	attr.Mode = filePerm 
+	if fi.m.options.Offline {
+		fmt.Printf("info %v\n", info)
```
Comment (sahib) [inline fuse/file.go]: Please remove that debug log.

File: fuse/file.go [hunk 2]
```diff
@@ -36,7 +37,18 @@ func (fi *File) Attr(ctx context.Context, attr *fuse.Attr) error {
...
+		isCached, err := fi.m.fs.IsCached(fi.path)
+		if err != nil || !isCached {
```
Comment (sahib) [inline fuse/file.go:45]: This will also show files as symlinks where ``IsCached`` errored for some reason. We should at least log the error.

File: fuse/file.go [hunk 3]
```diff
@@ -168,6 +180,16 @@ func (fi *File) Listxattr(ctx context.Context, req *fuse.ListxattrRequest, resp
...
 }
 
+// Readlink reads a symbolic link.
+// This call is triggered when OS tries to see where symlink points
+func (fi *File) Readlink(ctx context.Context, req *fuse.ReadlinkRequest) (string, error) {
+	info, err := fi.m.fs.Stat(fi.path)
+	if err != nil {
+		return "/brig/backend/ipfs/", err
+	}
+	return fmt.Sprintf("/brig/backend/ipfs/%s", info.BackendHash), nil
```
Comment (sahib) [inline fuse/file.go:193]: Hmm, not so sure about the intention of this feature. What would the user supposedly do with the link in here?
Programs that call ``readlink()`` will detect this as ``ENOENT`` and just show a broken link. The text above would be only seen if somebody calls the ``readlink`` utility on the file.

**Review by sahib — CHANGES_REQUESTED** [review]
Looks good to me overall, one clarification needed and two smaller nitpicks.

**Comment by sahib** [comment]
It might be also worth to add a test for this behavior.

File: fuse/file.go (hunk 2 above)
Comment (evgmik) [reply fuse/file.go:45]: Done with 3a5c46b

I have a question. The fuse files avoid using log facilities, i.e. `log.Debug()` and sparingly use `debugLog()`. Is there a deep reason for it? Is it used to enable/disable logging only for fuse module with `enableDebugLogs = false/true`  https://github.com/sahib/brig/blob/6140e52ffe5713c50f2ea01bb0cf9a0f0e69e799/fuse/fs.go#L15

File: fuse/file.go (hunk 1 above)
Comment (evgmik) [reply fuse/file.go]: done with 7e125c5

File: fuse/file.go (hunk 2 above)
Comment (sahib) [reply fuse/file.go:45]: No, I don't think there was a deeper reasons to it. FUSE debugging can get very spammy, so I wanted an easy flag I can toggle. Some day I will implement proper subsystem logging.

File: fuse/file.go (hunk 3 above)
Comment (evgmik) [reply fuse/file.go:193]: If we do not implement `Readlink` then tools like `ls` would spam the output with
```
ls: cannot read symbolic link '/tmp/zz/README.md': Input/output error
```
Where do we point a link to noncached file is good question. I chose to point it quite wordy link which somewhat describe the issue. This way
a user can get some hints without calling `brig` (if someone is using fuse, they probably are shielded from `brig`). Also one can do a shell only script to ask `ipfs` to download missing hash.

Comment (sahib) [reply fuse/file.go:193]: Okay. I guess that's good enough for now. Maybe later we could do some more tricks with the link content.

**Review by sahib — APPROVED** [review]
